import type { InferGetStaticPropsType, NextPage } from "next";
import Head from "next/head";
import { getAllPosts } from "./api/api.ts";

type Props = InferGetStaticPropsType<typeof getStaticProps>;

export const getStaticProps = async () => {
    const allPosts = getAllPosts(["slug", "title", "date", "tags"]);
    return {
        props: { allPosts },
    };
};

const Home: NextPage = ({ allPosts }) => {
    return (
        <div className="container m-8">
            <Head>
                <title>Kindness Home</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="container">
                <h1 className="text-5xl font-bold">Kindness</h1>
                <div className="grid grid-cols-4">
                    {allPosts.map((post) => (
                        <a href={post.slug} className="" key={post.slug}>
                            <h2>{post.title}</h2>
                            <p>{post.date}</p>
                        </a>
                    ))}
                </div>
            </main>
        </div>
    );
};

export default Home;
